[env:esp32-2432s028r]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = min_spiffs.csv
lib_deps =
    lovyan03/LovyanGFX@^1.2.31
    bblanchon/ArduinoJson@^7.2.0
build_flags =
    -O3
    -D CORE_DEBUG_LEVEL=0
